rbd: Set _snapshot_name to empty string.
Something later in the code, probably the size check,
assumes it exists and is set, and fails with:
   ERROR: 'IO' object has no attribute '_snapshot_name'
whenever trying to restore a backup to RBD.